name: Github commit to telegram

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # 此步骤使用 GitHub 的 https://github.com/actions/checkout
    - name: checkout actions
      uses: actions/checkout@v3

    # 设置python环境
    # 此步骤使用 GitHub 的 https://github.com/actions/setup-python
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    # 安装依赖
    - name: Install dependencies
      run: |
        mkdir tmp && cd tmp
        python -m pip install --upgrade pip
        pip install httpx

    # 发送通知
    - name: Send notice
      run: |
        cd tmp
        cp ../telegram_update.py ./
        python telegram_update.py ${{ secrets.TG_BOT_TOKEN }}
